### ISSUE TITLE
Load Meshes

### ISSUE THREAD

**Issue by paparyku** [Beg-in/vue-babylonjs#16] opened 2018-10-11 04:05 UTC
I love uses components with Babylon but there seems to be some sort of important missing feature. Hopefully, we can add obj... importer etc.

https://doc.babylonjs.com/how_to/load_from_any_file_type

**Comment by BrainBacon** [comment] 2018-10-12 15:38
This is a duplicate of #2

**Closed as completed by BrainBacon** 2018-10-12 15:38 UTC
Labels: duplicate
